USE [master]
GO

/****** Object:  Database [SportRegistrationSystem]    Script Date: 8/25/2015 4:12:26 PM ******/
CREATE DATABASE [SportRegistrationSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SportRegistrationSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SportRegistrationSystem.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SportRegistrationSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SportRegistrationSystem_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SportRegistrationSystem] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SportRegistrationSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SportRegistrationSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SportRegistrationSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SportRegistrationSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SportRegistrationSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SportRegistrationSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SportRegistrationSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [SportRegistrationSystem] SET  MULTI_USER 
GO

ALTER DATABASE [SportRegistrationSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SportRegistrationSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SportRegistrationSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SportRegistrationSystem] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SportRegistrationSystem] SET  READ_WRITE 
GO

