//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymnasticRegister.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SportRegistrationSystem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SportRegistrationSystem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GymnasticRegister.Resources.SportRegistrationSystem", typeof(SportRegistrationSystem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Quote :.
        /// </summary>
        internal static string lblAddQuote {
            get {
                return ResourceManager.GetString("lblAddQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Student.
        /// </summary>
        internal static string lblAddStudent {
            get {
                return ResourceManager.GetString("lblAddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age :.
        /// </summary>
        internal static string lblAge {
            get {
                return ResourceManager.GetString("lblAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string lblBack {
            get {
                return ResourceManager.GetString("lblBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for students who has not paid their fees for this month..
        /// </summary>
        internal static string lblCheckFormDesc {
            get {
                return ResourceManager.GetString("lblCheckFormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Payment.
        /// </summary>
        internal static string lblCheckPayment {
            get {
                return ResourceManager.GetString("lblCheckPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Students Cleared Payment Check.
        /// </summary>
        internal static string lblClearedPayment {
            get {
                return ResourceManager.GetString("lblClearedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMP Contact No :.
        /// </summary>
        internal static string lblContactNumber {
            get {
                return ResourceManager.GetString("lblContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date :.
        /// </summary>
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB :.
        /// </summary>
        internal static string lblDob {
            get {
                return ResourceManager.GetString("lblDob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName :.
        /// </summary>
        internal static string lblFullName {
            get {
                return ResourceManager.GetString("lblFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender :.
        /// </summary>
        internal static string lblGender {
            get {
                return ResourceManager.GetString("lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade :.
        /// </summary>
        internal static string lblGrade {
            get {
                return ResourceManager.GetString("lblGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert FullName.
        /// </summary>
        internal static string lblInvalidFullName {
            get {
                return ResourceManager.GetString("lblInvalidFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Login Name.
        /// </summary>
        internal static string lblInvalidLogin {
            get {
                return ResourceManager.GetString("lblInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password. Enter valid password with at least 8 characters.
        /// </summary>
        internal static string lblInvalidPassword {
            get {
                return ResourceManager.GetString("lblInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username.
        /// </summary>
        internal static string lblInvalidUsername {
            get {
                return ResourceManager.GetString("lblInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value added. Please confirm value inserted..
        /// </summary>
        internal static string lblInvalidValue {
            get {
                return ResourceManager.GetString("lblInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Paid :.
        /// </summary>
        internal static string lblLastPaid {
            get {
                return ResourceManager.GetString("lblLastPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string lblLoginFailed {
            get {
                return ResourceManager.GetString("lblLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup.
        /// </summary>
        internal static string lblLookup {
            get {
                return ResourceManager.GetString("lblLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Last Payment.
        /// </summary>
        internal static string lblNoLastPayment {
            get {
                return ResourceManager.GetString("lblNoLastPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payable Amount :.
        /// </summary>
        internal static string lblPayableAmt {
            get {
                return ResourceManager.GetString("lblPayableAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string lblPayment {
            get {
                return ResourceManager.GetString("lblPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment failed..
        /// </summary>
        internal static string lblPaymentFailed {
            get {
                return ResourceManager.GetString("lblPaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment has been successfully made..
        /// </summary>
        internal static string lblPaymentSuccess {
            get {
                return ResourceManager.GetString("lblPaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation :.
        /// </summary>
        internal static string lblPermission {
            get {
                return ResourceManager.GetString("lblPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string lblQuote {
            get {
                return ResourceManager.GetString("lblQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote List :.
        /// </summary>
        internal static string lblQuoteList {
            get {
                return ResourceManager.GetString("lblQuoteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string lblRegister {
            get {
                return ResourceManager.GetString("lblRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Failed.
        /// </summary>
        internal static string lblRegisterFailed {
            get {
                return ResourceManager.GetString("lblRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Successful.
        /// </summary>
        internal static string lblRegisterSuccess {
            get {
                return ResourceManager.GetString("lblRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark :.
        /// </summary>
        internal static string lblRemark {
            get {
                return ResourceManager.GetString("lblRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        internal static string lblReporting {
            get {
                return ResourceManager.GetString("lblReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Management.
        /// </summary>
        internal static string lblStaffManagement {
            get {
                return ResourceManager.GetString("lblStaffManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Management.
        /// </summary>
        internal static string lblStudentManagement {
            get {
                return ResourceManager.GetString("lblStudentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name :.
        /// </summary>
        internal static string lblStudentName {
            get {
                return ResourceManager.GetString("lblStudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string lblSubmit {
            get {
                return ResourceManager.GetString("lblSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username :.
        /// </summary>
        internal static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
    }
}
